<?xml version="1.0" encoding="utf-8" ?> 
<DUMMY>
  <LOCAL_VARIABLE id="CURRENT_DIR" value="$_DIR_$"/>
  <DEFINE>
    <!-- *********** LIGHT BACKGROUND ***********  -->
    <!-- sliver and gold knobs -->
    <PNS_GOLD_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/gold_knob.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_GOLD_KNOB_SYM base_type="PNS_GOLD_KNOB"/>    
    <PNS_SILVER_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/silver_knob.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_SILVER_KNOB_SYM base_type="PNS_SILVER_KNOB"/>  

    <!-- Chicken head knobs -->
    <PNS_BLACK_CHICKEN_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/black_chicken_knob.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLACK_CHICKEN_KNOB_SYM base_type="PNS_BLACK_CHICKEN_KNOB"/>
    <PNS_WHITE_CHICKEN_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/white_chicken_knob.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_WHITE_CHICKEN_KNOB_SYM base_type="PNS_WHITE_CHICKEN_KNOB"/>
    <PNS_CREAM_CHICKEN_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/cream_chicken_knob.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_CREAM_CHICKEN_KNOB_SYM base_type="PNS_CREAM_CHICKEN_KNOB"/>

    <!-- Skirted knobs -->
    <PNS_BLACK_SKIRTED_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/black_skirted_knob.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLACK_SKIRTED_KNOB_SYM base_type="PNS_BLACK_SKIRTED_KNOB"/>

    <!-- Stove knobs -->
    <PNS_BLUE_STOVE_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/blue_stove_knob.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLUE_STOVE_KNOB_SYM base_type="PNS_BLUE_STOVE_KNOB"/>
    <PNS_PINK_STOVE_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/pink_stove_knob.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_PINK_STOVE_KNOB_SYM base_type="PNS_PINK_STOVE_KNOB"/>
    <PNS_GREEN_STOVE_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/green_stove_knob.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_GREEN_STOVE_KNOB_SYM base_type="PNS_GREEN_STOVE_KNOB"/>

    <!-- Vintage knobs -->
    <PNS_BLACK_VINTAGE_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/black_vintage_knob.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLACK_VINTAGE_KNOB_SYM base_type="PNS_BLACK_VINTAGE_KNOB"/>
    <PNS_BLACK_VINTAGE_SMALL_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".4" image="$CURRENT_DIR$/black_vintage_knob.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLACK_VINTAGE_SMALL_KNOB_SYM base_type="PNS_BLACK_VINTAGE_SMALL_KNOB"/>

    <!-- Cupcake knobs -->
    <PNS_BLACK_CUPCAKE_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/black_cupcake_knob.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLACK_CUPCAKE_KNOB_SYM base_type="PNS_BLACK_CUPCAKE_KNOB"/>
    <PNS_CREAM_CUPCAKE_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/cream_cupcake_knob.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_CREAM_CUPCAKE_KNOB_SYM base_type="PNS_CREAM_CUPCAKE_KNOB"/>
    
    <!-- Metal knobs -->
    <PNS_BLACK_METAL_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/metal_black_knob.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLACK_METAL_KNOB_SYM base_type="PNS_BLACK_METAL_KNOB"/>
    <PNS_BLUE_METAL_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/metal_blue_knob.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLUE_METAL_KNOB_SYM base_type="PNS_BLUE_METAL_KNOB"/>
    <PNS_RED_METAL_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/metal_red_knob.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_RED_METAL_KNOB_SYM base_type="PNS_RED_METAL_KNOB"/>
    <PNS_SILVER_METAL_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/metal_silver_knob.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_SILVER_METAL_KNOB_SYM base_type="PNS_SILVER_METAL_KNOB"/>

    <!-- Studio knobs -->
    <PNS_BLACK_STUDIO_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/studio_black_knob.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLACK_STUDIO_KNOB_SYM base_type="PNS_BLACK_STUDIO_KNOB"/>
    <PNS_BLUE_STUDIO_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/studio_blue_knob.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLUE_STUDIO_KNOB_SYM base_type="PNS_BLUE_STUDIO_KNOB"/>
    <PNS_RED_STUDIO_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/studio_red_knob.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_RED_STUDIO_KNOB_SYM base_type="PNS_RED_STUDIO_KNOB"/>
    <PNS_GREY_STUDIO_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/studio_grey_knob.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_GREY_STUDIO_KNOB_SYM base_type="PNS_GREY_STUDIO_KNOB"/>


    <!-- Mixer knobs -->
    <PNS_BLUE_MIXER_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/mixer_blue_knob.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLUE_MIXER_KNOB_SYM base_type="PNS_BLUE_MIXER_KNOB"/>
    <PNS_GREEN_MIXER_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/mixer_green_knob.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_GREEN_MIXER_KNOB_SYM base_type="PNS_GREEN_MIXER_KNOB"/>
    <PNS_RED_MIXER_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/mixer_red_knob.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_RED_MIXER_KNOB_SYM base_type="PNS_RED_MIXER_KNOB"/>

    <!-- Fluted knobs -->
    <PNS_SILVER_FLUTED_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/fluted_silver_knob.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_SILVER_FLUTED_KNOB_SYM base_type="PNS_SILVER_FLUTED_KNOB"/>
    <PNS_GOLD_FLUTED_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/fluted_gold_knob.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_GOLD_FLUTED_KNOB_SYM base_type="PNS_GOLD_FLUTED_KNOB"/>


    <!-- *********** DARK BACKGROUND ************* -->
    <!-- sliver and gold knobs -->
    <PNS_GOLD_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/gold_knob_b.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_GOLD_B_KNOB_SYM base_type="PNS_GOLD_B_KNOB"/>
    <PNS_SILVER_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/silver_knob_b.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_SILVER_B_KNOB_SYM base_type="PNS_SILVER_B_KNOB"/>

    <PNS_BLACK_BULLET_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/bullet_black_knob_b.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLACK_BULLET_B_KNOB_SYM base_type="PNS_BLACK_BULLET_B_KNOB"/>    
    <PNS_GOLD_BULLET_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/bullet_gold_knob_b.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_GOLD_BULLET_B_KNOB_SYM base_type="PNS_GOLD_BULLET_B_KNOB"/>    
    <PNS_SILVER_BULLET_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/bullet_silver_knob_b.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_SILVER_BULLET_B_KNOB_SYM base_type="PNS_SILVER_BULLET_B_KNOB"/>  

    <!-- Chicken head knobs -->
    <PNS_BLACK_CHICKEN_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/black_chicken_knob_b.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLACK_CHICKEN_B_KNOB_SYM base_type="PNS_BLACK_CHICKEN_B_KNOB"/>
    <PNS_WHITE_CHICKEN_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/white_chicken_knob_b.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_WHITE_CHICKEN_B_KNOB_SYM base_type="PNS_WHITE_CHICKEN_B_KNOB"/>
    <PNS_CREAM_CHICKEN_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/cream_chicken_knob_b.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_CREAM_CHICKEN_B_KNOB_SYM base_type="PNS_CREAM_CHICKEN_B_KNOB"/>

    <!-- Vintage knobs -->
    <PNS_BLACK_VINTAGE_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/black_vintage_knob_b.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLACK_VINTAGE_B_KNOB_SYM base_type="PNS_BLACK_VINTAGE_B_KNOB"/>

    <PNS_BLACK_VINTAGE_SMALL_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".4" image="$CURRENT_DIR$/black_vintage_knob_b.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLACK_VINTAGE_SMALL_B_KNOB_SYM base_type="PNS_BLACK_VINTAGE_SMALL_B_KNOB"/>
    
    <!-- Skirted knobs -->
    <PNS_BLACK_SKIRTED_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/black_skirted_knob_b.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLACK_SKIRTED_B_KNOB_SYM base_type="PNS_BLACK_SKIRTED_B_KNOB"/>

    <PNS_BLUE_STOVE_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/blue_stove_knob_b.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLUE_STOVE_B_KNOB_SYM base_type="PNS_BLUE_STOVE_B_KNOB"/>
    <PNS_PINK_STOVE_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/pink_stove_knob_b.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_PINK_STOVE_B_KNOB_SYM base_type="PNS_PINK_STOVE_B_KNOB"/>
    <PNS_GREEN_STOVE_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/green_stove_knob_b.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_GREEN_STOVE_B_KNOB_SYM base_type="PNS_GREEN_STOVE_B_KNOB"/>
    
    <!-- Cupcake knobs -->
    <PNS_BLACK_CUPCAKE_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/black_cupcake_knob_b.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLACK_CUPCAKE_B_KNOB_SYM base_type="PNS_BLACK_CUPCAKE_B_KNOB"/>
    <PNS_CREAM_CUPCAKE_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/cream_cupcake_knob_b.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_CREAM_CUPCAKE_B_KNOB_SYM base_type="PNS_CREAM_CUPCAKE_B_KNOB"/>

    <!-- Metal knobs -->
    <PNS_BLACK_METAL_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/metal_black_knob_b.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLACK_METAL_B_KNOB_SYM base_type="PNS_BLACK_METAL_B_KNOB"/>
    <PNS_BLUE_METAL_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/metal_blue_knob_b.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLUE_METAL_B_KNOB_SYM base_type="PNS_BLUE_METAL_B_KNOB"/>
    <PNS_RED_METAL_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/metal_red_knob_b.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_RED_METAL_B_KNOB_SYM base_type="PNS_RED_METAL_B_KNOB"/>
    <PNS_SILVER_METAL_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/metal_silver_knob_b.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_SILVER_METAL_B_KNOB_SYM base_type="PNS_SILVER_METAL_B_KNOB"/>

    <!-- Studio knobs -->
    <PNS_BLACK_STUDIO_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/studio_black_knob_b.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLACK_STUDIO_B_KNOB_SYM base_type="PNS_BLACK_STUDIO_B_KNOB"/>
    <PNS_BLUE_STUDIO_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/studio_blue_knob_b.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLUE_STUDIO_B_KNOB_SYM base_type="PNS_BLUE_STUDIO_B_KNOB"/>
    <PNS_RED_STUDIO_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/studio_red_knob_b.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_RED_STUDIO_B_KNOB_SYM base_type="PNS_RED_STUDIO_B_KNOB"/>
    <PNS_GREY_STUDIO_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/studio_grey_knob_b.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_GREY_STUDIO_B_KNOB_SYM base_type="PNS_GREY_STUDIO_B_KNOB"/>

    <!-- Mixer knobs -->
    <PNS_BLUE_MIXER_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/mixer_blue_knob_b.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLUE_MIXER_B_KNOB_SYM base_type="PNS_BLUE_MIXER_B_KNOB"/>
    <PNS_GREEN_MIXER_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/mixer_green_knob_b.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_GREEN_MIXER_B_KNOB_SYM base_type="PNS_GREEN_MIXER_B_KNOB"/>
    <PNS_RED_MIXER_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/mixer_red_knob_b.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_RED_MIXER_B_KNOB_SYM base_type="PNS_RED_MIXER_B_KNOB"/>

    <!-- Fluted knobs -->
    <PNS_SILVER_FLUTED_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/fluted_silver_knob_b.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_SILVER_FLUTED_B_KNOB_SYM base_type="PNS_SILVER_FLUTED_B_KNOB"/>
    <PNS_GOLD_FLUTED_B_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="151" image_scaling=".5" image="$CURRENT_DIR$/fluted_gold_knob_b.png" images_count="151" positions_count="151" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_GOLD_FLUTED_B_KNOB_SYM base_type="PNS_GOLD_FLUTED_B_KNOB"/>

    <!-- ************ NEUTRAL *************  -->
    <PNS_BLACK_STOVE_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/black_stove_knob.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLACK_STOVE_KNOB_SYM base_type="PNS_BLACK_STOVE_KNOB"/>
    <PNS_WHITE_STOVE_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/white_stove_knob.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_WHITE_STOVE_KNOB_SYM base_type="PNS_WHITE_STOVE_KNOB"/>
    <PNS_ORANGE_STOVE_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/orange_stove_knob.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_ORANGE_STOVE_KNOB_SYM base_type="PNS_ORANGE_STOVE_KNOB"/>
    <PNS_BLACKORANGE_STOVE_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image_scaling=".5" image="$CURRENT_DIR$/black-orange_stove_knob.png" images_count="147" positions_count="147" image_orientation="vertical" cursor="system::hand" ignore_mask_files="true"/>
    <PNS_BLACKORANGE_STOVE_KNOB_SYM base_type="PNS_BLACKORANGE_STOVE_KNOB"/>
    <PNS_BLUE_FLAT_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image="$CURRENT_DIR$/blue_flat_knob.svg" opaque_mouse_mask="true" images_count="73" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_file="true" opacity="60%"/>
    <PNS_BLUE_FLAT_KNOB_SYM base_type="IMAGE_PARAM_KNOB" pixel_range="147" image="$CURRENT_DIR$/blue_flat_knob_sym.svg" opaque_mouse_mask="true" images_count="73" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_file="true" opacity="60%"/>
    <PNS_GREY_FLAT_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image="$CURRENT_DIR$/grey_flat_knob.svg" opaque_mouse_mask="true" images_count="73" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_file="true" opacity="60%"/>
    <PNS_GREY_FLAT_KNOB_SYM base_type="IMAGE_PARAM_KNOB" pixel_range="147" image="$CURRENT_DIR$/grey_flat_knob.svg" opaque_mouse_mask="true" images_count="73" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_file="true" opacity="60%"/>
    <PNS_ORANGE_FLAT_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image="$CURRENT_DIR$/orange_flat_knob.svg" opaque_mouse_mask="true" images_count="73" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_file="true"/>
    <PNS_ORANGE_FLAT_KNOB_SYM base_type="IMAGE_PARAM_KNOB" pixel_range="147" image="$CURRENT_DIR$/orange_flat_knob.svg" opaque_mouse_mask="true" images_count="73" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_file="true"/>
    <PNS_YELLOW_FLAT_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image="$CURRENT_DIR$/yellow_flat_knob.svg" opaque_mouse_mask="true" images_count="73" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_file="true"/>
    <PNS_YELLOW_FLAT_KNOB_SYM base_type="IMAGE_PARAM_KNOB" pixel_range="147" image="$CURRENT_DIR$/yellow_flat_knob.svg" opaque_mouse_mask="true" images_count="73" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_file="true"/>
    <PNS_GREEN_FLAT_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image="$CURRENT_DIR$/green_flat_knob.svg" opaque_mouse_mask="true" images_count="73" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_file="true"/>
    <PNS_GREEN_FLAT_KNOB_SYM base_type="IMAGE_PARAM_KNOB" pixel_range="147" image="$CURRENT_DIR$/green_flat_knob.svg" opaque_mouse_mask="true" images_count="73" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_file="true"/>
    <PNS_RED_FLAT_KNOB base_type="IMAGE_PARAM_KNOB" pixel_range="147" image="$CURRENT_DIR$/red_flat_knob.svg" opaque_mouse_mask="true" images_count="73" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_file="true"/>
    <PNS_RED_FLAT_KNOB_SYM base_type="IMAGE_PARAM_KNOB" pixel_range="147" image="$CURRENT_DIR$/red_flat_knob.svg" opaque_mouse_mask="true" images_count="73" positions_count="101" image_orientation="vertical" cursor="system::hand" ignore_mask_file="true"/>

    <!-- ************ FROM BCA DEFAULT THEME *************  -->
    <PNS_SILVER_BLUE_MODERN_KNOB base_type="THEME_KNOB_CHANNEL1"/>
    <PNS_SILVER_BLUE_MODERN_KNOB_SYM base_type="THEME_KNOB_CHANNEL1_SYM"/>
    <PNS_SILVER_PINK_MODERN_KNOB base_type="THEME_KNOB_CHANNEL2"/>
    <PNS_SILVER_PINK_MODERN_KNOB_SYM base_type="THEME_KNOB_CHANNEL2_SYM"/>
    <PNS_BLACK_BLUE_MODERN_KNOB base_type="THEME_ALT_KNOB_CHANNEL1"/>
    <PNS_BLACK_BLUE_MODERN_KNOB_SYM base_type="THEME_ALT_KNOB_CHANNEL1_SYM"/>
    <PNS_BLACK_PINK_MODERN_KNOB base_type="THEME_ALT_KNOB_CHANNEL2"/>
    <PNS_BLACK_PINK_MODERN_KNOB_SYM base_type="THEME_ALT_KNOB_CHANNEL2_SYM"/>

    <!-- ************ FADERS ************************ -->
    <PNS_FADER base_type="THEME_FADER" h_offset="3" height="120"/>
    <PNS_SLIM_FADER base_type="THEME_SLIM_FADER" h_offset="1" height="120"/>
    <PNS_FLAT_FADER base_type="THEME_GRAPH_SLIDER" height="110"/>

  </DEFINE>
</DUMMY>